# Generated by Django 4.0.2 on 2022-02-28 03:57

from django.db import migrations, models
import store.validator


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store/images', validators=[store.validator.validate_file_size]),
        ),
    ]
